language: cpp
compiler:
  - gcc
  - clang
before_script:
   - sudo apt-get update -qq
   - sudo apt-get install -y openmpi-bin
   - sudo apt-get install -y libboost-all-dev
   - sudo apt-get install -y fftw3-dev
script:
   - cd tools
   - ./build_k52_run_examples.sh
